export const transactions = [
  {
    id: 1,
    name: "Groceries",
    amount: 65.0,
    currency: "€",
    date: "2024-04-26",
    description: "Weekly grocery shopping",
    category: "Groceries",
    paymentMethod: "Cash",
    direction: "Expense",
  },
  {
    id: 2,
    name: "Rent",
    amount: 1000.0,
    currency: "€",
    date: "2024-04-26",
    description: "Monthly rent payment",
    category: "Housing",
    paymentMethod: "Card",
    direction: "Expense",
  },
  {
    id: 3,
    name: "Car Insurance",
    amount: 150.0,
    currency: "€",
    date: "2024-04-26",
    description: "Monthly car insurance premium",
    category: "Insurance",
    paymentMethod: "Cash",
    direction: "Expense",
  },
  {
    id: 4,
    name: "Dinner",
    amount: 40.0,
    currency: "€",
    date: "2024-04-26",
    description: "Dinner at a restaurant",
    category: "Dining Out",
    paymentMethod: "Card",
    direction: "Expense",
  },
  {
    id: 5,
    name: "Gym Membership",
    amount: 50.0,
    currency: "€",
    date: "2024-04-26",
    description: "Monthly gym membership fee",
    category: "Fitness",
    paymentMethod: "Cash",
    direction: "Expense",
  },
  {
    id: 6,
    name: "Gasoline",
    amount: 70.0,
    currency: "€",
    date: "2024-04-26",
    description: "Refueling car with gasoline",
    category: "Transportation",
    paymentMethod: "Cash",
    direction: "Expense",
  },
  {
    id: 7,
    name: "Movie Tickets",
    amount: 25.0,
    currency: "€",
    date: "2024-04-26",
    description: "Tickets for a movie night",
    category: "Entertainment",
    paymentMethod: "Card",
    direction: "Expense",
  },
  {
    id: 8,
    name: "Hobby Supplies",
    amount: 30.0,
    currency: "€",
    date: "2024-04-26",
    description: "Purchase of hobby supplies",
    category: "Hobbies",
    paymentMethod: "Card",
    direction: "Expense",
  },
  {
    id: 9,
    name: "Salary",
    amount: 2000.0,
    currency: "€",
    date: "2024-04-26",
    description: "Pain Money monthly",
    category: "Salary",
    paymentMethod: "Cash",
    direction: "Income",
  },
  {
    id: 10,
    name: "Internet Bill",
    amount: 45.0,
    currency: "€",
    date: "2024-04-26",
    description: "Monthly internet service bill",
    category: "Utilities",
    paymentMethod: "Card",
    direction: "Expense",
  },
];
