export const transactions = [
	{
		id: 1,
		name: "Weekly Grocery Shopping",
		amount: 65.0,
		currency: "€",
		date: "2024-03-05",
		description: "Purchase of groceries for the week",
		category: "Groceries",
		paymentMethod: "Cash",
		direction: "Expense",
	},
	{
		id: 2,
		name: "Monthly Rent",
		amount: 1000.0,
		currency: "€",
		date: "2024-03-15",
		description: "Payment of monthly rent",
		category: "Housing",
		paymentMethod: "Bank Transfer",
		direction: "Expense",
	},
	{
		id: 3,
		name: "Gas Bill",
		amount: 50.0,
		currency: "€",
		date: "2024-03-20",
		description: "Monthly gas bill",
		category: "Utilities",
		paymentMethod: "Direct Debit",
		direction: "Expense",
	},
	{
		id: 4,
		name: "Salary",
		amount: 2500.0,
		currency: "€",
		date: "2024-03-31",
		description: "Monthly salary payment",
		category: "Salary",
		paymentMethod: "Bank Transfer",
		direction: "Income",
	},
	{
		id: 5,
		name: "Health Insurance Premium",
		amount: 120.0,
		currency: "€",
		date: "2024-04-05",
		description: "Monthly health insurance premium",
		category: "Insurance",
		paymentMethod: "Credit Card",
		direction: "Expense",
	},
	{
		id: 6,
		name: "Electricity Bill",
		amount: 80.0,
		currency: "€",
		date: "2024-04-10",
		description: "Monthly electricity bill",
		category: "Utilities",
		paymentMethod: "Direct Debit",
		direction: "Expense",
	},
	{
		id: 7,
		name: "Dinner at Restaurant",
		amount: 40.0,
		currency: "€",
		date: "2024-04-15",
		description: "Dinner with friends at a restaurant",
		category: "Groceries",
		paymentMethod: "Credit Card",
		direction: "Expense",
	},
	{
		id: 8,
		name: "Internet Bill",
		amount: 35.0,
		currency: "€",
		date: "2024-04-20",
		description: "Monthly internet service bill",
		category: "Utilities",
		paymentMethod: "Bank Transfer",
		direction: "Expense",
	},
	{
		id: 9,
		name: "Shopping",
		amount: 70.0,
		currency: "€",
		date: "2024-04-25",
		description: "Shopping for clothing and accessories",
		category: "Groceries",
		paymentMethod: "Cash",
		direction: "Expense",
	},
	{
		id: 10,
		name: "Monthly Salary",
		amount: 2800.0,
		currency: "€",
		date: "2024-04-30",
		description: "Monthly salary payment",
		category: "Salary",
		paymentMethod: "Bank Transfer",
		direction: "Income",
	},
	{
		id: 11,
		name: "Weekly Grocery Shopping",
		amount: 60.0,
		currency: "€",
		date: "2024-05-05",
		description: "Purchase of groceries for the week",
		category: "Groceries",
		paymentMethod: "Credit Card",
		direction: "Expense",
	},
	{
		id: 12,
		name: "Water Bill",
		amount: 30.0,
		currency: "€",
		date: "2024-05-10",
		description: "Monthly water bill",
		category: "Utilities",
		paymentMethod: "Direct Debit",
		direction: "Expense",
	},
	{
		id: 13,
		name: "Health Insurance Premium",
		amount: 120.0,
		currency: "€",
		date: "2024-05-15",
		description: "Monthly health insurance premium",
		category: "Insurance",
		paymentMethod: "Bank Transfer",
		direction: "Expense",
	},
	{
		id: 14,
		name: "Dinner at Restaurant",
		amount: 45.0,
		currency: "€",
		date: "2024-05-20",
		description: "Celebratory dinner at a restaurant",
		category: "Groceries",
		paymentMethod: "Cash",
		direction: "Expense",
	},
	{
		id: 15,
		name: "Gasoline",
		amount: 50.0,
		currency: "€",
		date: "2024-05-25",
		description: "Refueling car with gasoline",
		category: "Utilities",
		paymentMethod: "Credit Card",
		direction: "Expense",
	},
	{
		id: 16,
		name: "Monthly Salary",
		amount: 3000.0,
		currency: "€",
		date: "2024-05-30",
		description: "Monthly salary payment",
		category: "Salary",
		paymentMethod: "Bank Transfer",
		direction: "Income",
	},
	{
		id: 17,
		name: "Electricity Bill",
		amount: 85.0,
		currency: "€",
		date: "2024-03-10",
		description: "Monthly electricity bill",
		category: "Utilities",
		paymentMethod: "Direct Debit",
		direction: "Expense",
	},
	{
		id: 18,
		name: "Rent",
		amount: 1050.0,
		currency: "€",
		date: "2024-03-25",
		description: "Monthly rent payment",
		category: "Housing",
		paymentMethod: "Bank Transfer",
		direction: "Expense",
	},
	{
		id: 19,
		name: "Salary",
		amount: 2600.0,
		currency: "€",
		date: "2024-05-01",
		description: "Monthly salary payment",
		category: "Salary",
		paymentMethod: "Bank Transfer",
		direction: "Income",
	},
	{
		id: 20,
		name: "Car Insurance Premium",
		amount: 150.0,
		currency: "€",
		date: "2024-04-18",
		description: "Annual car insurance premium",
		category: "Insurance",
		paymentMethod: "Credit Card",
		direction: "Expense",
	},
	{
		id: 21,
		name: "Weekly Grocery Shopping",
		amount: 70.0,
		currency: "€",
		date: "2024-03-12",
		description: "Weekly grocery shopping",
		category: "Groceries",
		paymentMethod: "Cash",
		direction: "Expense",
	},
	{
		id: 22,
		name: "Gas Bill",
		amount: 55.0,
		currency: "€",
		date: "2024-03-18",
		description: "Monthly gas bill",
		category: "Utilities",
		paymentMethod: "Direct Debit",
		direction: "Expense",
	},
	{
		id: 23,
		name: "Monthly Salary",
		amount: 2700.0,
		currency: "€",
		date: "2024-05-05",
		description: "Monthly salary payment",
		category: "Salary",
		paymentMethod: "Bank Transfer",
		direction: "Income",
	},
	{
		id: 24,
		name: "Dinner at Restaurant",
		amount: 50.0,
		currency: "€",
		date: "2024-03-22",
		description: "Dinner at a fancy restaurant",
		category: "Groceries",
		paymentMethod: "Credit Card",
		direction: "Expense",
	},
	{
		id: 25,
		name: "Internet Bill",
		amount: 40.0,
		currency: "€",
		date: "2024-04-29",
		description: "Monthly internet service bill",
		category: "Utilities",
		paymentMethod: "Bank Transfer",
		direction: "Expense",
	},
	{
		id: 26,
		name: "Monthly Rent",
		amount: 1100.0,
		currency: "€",
		date: "2024-03-08",
		description: "Monthly rent payment",
		category: "Housing",
		paymentMethod: "Bank Transfer",
		direction: "Expense",
	},
	{
		id: 27,
		name: "Water Bill",
		amount: 35.0,
		currency: "€",
		date: "2024-04-12",
		description: "Monthly water bill",
		category: "Utilities",
		paymentMethod: "Direct Debit",
		direction: "Expense",
	},
	{
		id: 28,
		name: "Groceries",
		amount: 75.0,
		currency: "€",
		date: "2024-05-14",
		description: "Weekly grocery shopping",
		category: "Groceries",
		paymentMethod: "Cash",
		direction: "Expense",
	},
	{
		id: 29,
		name: "Salary",
		amount: 2800.0,
		currency: "€",
		date: "2024-04-02",
		description: "Monthly salary payment",
		category: "Salary",
		paymentMethod: "Bank Transfer",
		direction: "Income",
	},
	{
		id: 30,
		name: "Car Insurance Premium",
		amount: 150.0,
		currency: "€",
		date: "2024-05-20",
		description: "Annual car insurance premium",
		category: "Insurance",
		paymentMethod: "Credit Card",
		direction: "Expense",
	},
];
