export const transactions = [
  {
    id: "1",
    name: "apples",
    amount: 50,
    currency: "€",
    date: "2024-04-26",
    description: "an apple a day keeps the doctor away",
    category: "groceries",
    paymentMethod: "cash",
    direction: "expense",
  },
  {
    id: "2",
    name: "rent",
    amount: 500,
    currency: "€",
    date: "2024-04-26",
    description: "monthly rent",
    category: "housing",
    paymentMethod: "card",
    direction: "expense",
  },
  {
    id: "3",
    name: "drinks",
    amount: 25,
    currency: "€",
    date: "2024-04-26",
    description: "drinks okellys pub",
    category: "leisure",
    paymentMethod: "cash",
    direction: "expense",
  },
  {
    id: "4",
    name: "salary",
    amount: 1000,
    currency: "€",
    date: "2024-04-26",
    description: "salary form work",
    category: "work",
    paymentMethod: "card",
    direction: "income",
  },
];
